package com.companyblog.data.model;
// Generated Nov 26, 2018 9:37:50 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Answers generated by hbm2java
 */
@Entity
@Table(name="answers"
    ,catalog="companyblog"
)
public class Answers  implements java.io.Serializable {


     private Integer id;
     private Questions questions;
     private Users users;
     private String topic;

    public Answers() {
    }

	
    public Answers(Questions questions, Users users) {
        this.questions = questions;
        this.users = users;
    }
    public Answers(Questions questions, Users users, String topic) {
       this.questions = questions;
       this.users = users;
       this.topic = topic;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="QuestionId", nullable=false)
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UserId", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }

    
    @Column(name="Topic", length=70)
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }




}


