package com.companyblog.data.model;
// Generated Oct 13, 2018 10:23:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AnswersquestionsId generated by hbm2java
 */
@Embeddable
public class AnswersquestionsId  implements java.io.Serializable {


     private Integer questionId;
     private Integer anwersId;

    public AnswersquestionsId() {
    }

    public AnswersquestionsId(Integer questionId, Integer anwersId) {
       this.questionId = questionId;
       this.anwersId = anwersId;
    }
   


    @Column(name="QuestionId")
    public Integer getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }


    @Column(name="AnwersId")
    public Integer getAnwersId() {
        return this.anwersId;
    }
    
    public void setAnwersId(Integer anwersId) {
        this.anwersId = anwersId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AnswersquestionsId) ) return false;
		 AnswersquestionsId castOther = ( AnswersquestionsId ) other; 
         
		 return ( (this.getQuestionId()==castOther.getQuestionId()) || ( this.getQuestionId()!=null && castOther.getQuestionId()!=null && this.getQuestionId().equals(castOther.getQuestionId()) ) )
 && ( (this.getAnwersId()==castOther.getAnwersId()) || ( this.getAnwersId()!=null && castOther.getAnwersId()!=null && this.getAnwersId().equals(castOther.getAnwersId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getQuestionId() == null ? 0 : this.getQuestionId().hashCode() );
         result = 37 * result + ( getAnwersId() == null ? 0 : this.getAnwersId().hashCode() );
         return result;
   }   


}


