package com.companyblog.data.model;
// Generated Oct 13, 2018 10:23:32 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Answersquestions generated by hbm2java
 */
@Entity
@Table(name="answersquestions"
    ,catalog="companyblog"
)
public class Answersquestions  implements java.io.Serializable {


     private AnswersquestionsId id;
     private Answers answers;
     private Questions questions;

    public Answersquestions() {
    }

	
    public Answersquestions(AnswersquestionsId id) {
        this.id = id;
    }
    public Answersquestions(AnswersquestionsId id, Answers answers, Questions questions) {
       this.id = id;
       this.answers = answers;
       this.questions = questions;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="questionId", column=@Column(name="QuestionId") ), 
        @AttributeOverride(name="anwersId", column=@Column(name="AnwersId") ) } )
    public AnswersquestionsId getId() {
        return this.id;
    }
    
    public void setId(AnswersquestionsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="AnwersId", insertable=false, updatable=false)
    public Answers getAnswers() {
        return this.answers;
    }
    
    public void setAnswers(Answers answers) {
        this.answers = answers;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="QuestionId", insertable=false, updatable=false)
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }




}


