package com.companyblog.data.model;
// Generated Oct 13, 2018 10:23:32 AM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * QuestionsUser generated by hbm2java
 */
@Entity
@Table(name="questions_user"
    ,catalog="companyblog"
)
public class QuestionsUser  implements java.io.Serializable {


     private QuestionsUserId id;
     private Questions questions;
     private Users users;

    public QuestionsUser() {
    }

    public QuestionsUser(QuestionsUserId id, Questions questions, Users users) {
       this.id = id;
       this.questions = questions;
       this.users = users;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="questionId", column=@Column(name="QuestionId", nullable=false) ), 
        @AttributeOverride(name="userId", column=@Column(name="UserId", nullable=false) ) } )
    public QuestionsUserId getId() {
        return this.id;
    }
    
    public void setId(QuestionsUserId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="QuestionId", nullable=false, insertable=false, updatable=false)
    public Questions getQuestions() {
        return this.questions;
    }
    
    public void setQuestions(Questions questions) {
        this.questions = questions;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="UserId", nullable=false, insertable=false, updatable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }




}


