package com.companyblog.data.model;
// Generated Oct 13, 2018 10:23:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Questions generated by hbm2java
 */
@Entity
@Table(name="questions"
    ,catalog="companyblog"
)
public class Questions  implements java.io.Serializable {


     private Integer id;
     private String topic;
     private Set<Answersquestions> answersquestionses = new HashSet<Answersquestions>(0);
     private Set<QuestionsUser> questionsUsers = new HashSet<QuestionsUser>(0);

    public Questions() {
    }

    public Questions(String topic, Set<Answersquestions> answersquestionses, Set<QuestionsUser> questionsUsers) {
       this.topic = topic;
       this.answersquestionses = answersquestionses;
       this.questionsUsers = questionsUsers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Topic", length=70)
    public String getTopic() {
        return this.topic;
    }
    
    public void setTopic(String topic) {
        this.topic = topic;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="questions")
    public Set<Answersquestions> getAnswersquestionses() {
        return this.answersquestionses;
    }
    
    public void setAnswersquestionses(Set<Answersquestions> answersquestionses) {
        this.answersquestionses = answersquestionses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="questions")
    public Set<QuestionsUser> getQuestionsUsers() {
        return this.questionsUsers;
    }
    
    public void setQuestionsUsers(Set<QuestionsUser> questionsUsers) {
        this.questionsUsers = questionsUsers;
    }




}


