package com.companyblog.data.model;
// Generated Oct 13, 2018 10:23:32 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * QuestionsUserId generated by hbm2java
 */
@Embeddable
public class QuestionsUserId  implements java.io.Serializable {


     private int questionId;
     private int userId;

    public QuestionsUserId() {
    }

    public QuestionsUserId(int questionId, int userId) {
       this.questionId = questionId;
       this.userId = userId;
    }
   


    @Column(name="QuestionId", nullable=false)
    public int getQuestionId() {
        return this.questionId;
    }
    
    public void setQuestionId(int questionId) {
        this.questionId = questionId;
    }


    @Column(name="UserId", nullable=false)
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof QuestionsUserId) ) return false;
		 QuestionsUserId castOther = ( QuestionsUserId ) other; 
         
		 return (this.getQuestionId()==castOther.getQuestionId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getQuestionId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


