package com.companyblog.data.model;
// Generated Oct 13, 2018 10:23:32 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="companyblog"
)
public class Users  implements java.io.Serializable {


     private Integer id;
     private String email;
     private Set<QuestionsUser> questionsUsers = new HashSet<QuestionsUser>(0);

    public Users() {
    }

    public Users(String email, Set<QuestionsUser> questionsUsers) {
       this.email = email;
       this.questionsUsers = questionsUsers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Email", length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="users")
    public Set<QuestionsUser> getQuestionsUsers() {
        return this.questionsUsers;
    }
    
    public void setQuestionsUsers(Set<QuestionsUser> questionsUsers) {
        this.questionsUsers = questionsUsers;
    }




}


